### ISSUE TITLE
private Integer indexForAccount(Account account) {} -- accumulator doesn't reset

### ISSUE THREAD

**Issue by Davidx7** [polychrom/cordova-android-accountmanager#7]
#PROBLEM: 
If you request multiple times the getAccountsByType() with type = null, and get all accounts, on every request you get a higher ID, because it's always using the same var. 

Add a simple 
//-->FIX:
this.accumulator = 0;
in the public boolean execute() function, at the beginning, so each time you execute your counter will start from 0.

**Comment by mwheeler** [comment]
Thanks for the bug report, the accumulator was fine as best I can tell (it's supposed to be a statically incrementing number for the duration of the process, not reset each call) - the problem was incorrect equality (android seems to return new Account objects each time, thus == always returns false - causing me to think I'd never seen the account before, and assigning them a new ID despite them already being registered in the map).

Switching to .equals fixed the problem I believe, let me know if you still have any issues.
